version: '3'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - environment=development
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    entrypoint: /entrypoint.sh
    environment:
      - ws_back_url=http://localhost:5000
    volumes:
      - ./front:/usr/share/nginx/html