# points to the python back image using app.py and the dockerfile in the back directory
# also adds the frontend service using entrypoint.sh and the dockerfile in the front directory
version: '3'
services:
  back:
    build: ./back
    ports:
      - "5000:5000"
  front:
    build: ./front
    ports:
      - "3000:3000"
    entrypoint: /entrypoint.sh
    depends_on:
      - back